"""Validate weekly training references, progression, mappings, and workload."""

import argparse
import json

from sqlalchemy import Integer, cast

from app.database import SessionLocal
from app.models.curriculum_video import CurriculumVideo
from app.models.quiz import Quiz
from app.models.training import TrainingWeek, TrainingWeekActivity
from app.services.training_service import validate_training_curriculum


def _cell(value) -> str:
    return str(value).replace("|", "\\|")


def _markdown_report(db, result: dict) -> str:
    rows = (
        db.query(TrainingWeekActivity, TrainingWeek, CurriculumVideo)
        .join(TrainingWeek, TrainingWeek.id == TrainingWeekActivity.training_week_id)
        .join(CurriculumVideo, CurriculumVideo.id == cast(TrainingWeekActivity.content_ref, Integer))
        .filter(TrainingWeek.is_active.is_(True), TrainingWeekActivity.activity_type == "video")
        .order_by(TrainingWeek.display_order, TrainingWeekActivity.display_order)
        .all()
    )
    quiz_ids = {
        int((activity.metadata_json or {}).get("quiz_id"))
        for activity, _, _ in rows
        if str((activity.metadata_json or {}).get("quiz_id", "")).isdigit()
    }
    quizzes = {
        quiz.id: quiz for quiz in db.query(Quiz).filter(Quiz.id.in_(quiz_ids)).all()
    }
    lines = [
        "# My Training video-to-quiz mapping audit",
        "",
        "Generated by `backend/scripts/validate_training_curriculum.py --markdown` from the reviewed curriculum.",
        "",
        "| Video ID | Video title | Week | Assigned quiz ID | Quiz title | Mapping basis | Confidence |",
        "|---:|---|---:|---:|---|---|---|",
    ]
    for activity, week, video in rows:
        metadata = activity.metadata_json or {}
        quiz_id = int(metadata["quiz_id"])
        quiz = quizzes.get(quiz_id)
        lines.append(
            f"| {video.id} | {_cell(video.title)} | {week.week_number} | {quiz_id} | "
            f"{_cell(quiz.title if quiz else 'INVALID')} | "
            f"{metadata.get('quiz_mapping_basis', 'missing')} | {metadata.get('quiz_mapping_confidence', 'missing')} |"
        )
    lines.extend([
        "",
        "## Beginner workload audit",
        "",
        "| Week | Topic | Required items | Video minutes | Practice items | Estimated workload | Optional items |",
        "|---:|---|---:|---:|---:|---:|---:|",
    ])
    for workload in result["workload"]:
        practice = sum(workload[key] for key in (
            "required_guided_labs",
            "required_networking_labs",
            "required_support_tickets",
            "required_capstones",
        ))
        lines.append(
            f"| {workload['week_number']} | {_cell(workload['topic'])} | "
            f"{workload['required_items']} | {workload['required_video_minutes']} | {practice} | "
            f"{workload['estimated_minutes']} min | {workload['optional_items']} |"
        )
    lines.extend([
        "",
        f"Validation result: **{'PASS' if result['valid'] else 'FAIL'}** — "
        f"{result['mapped_video_count']} of {result['enabled_video_count']} enabled videos mapped.",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--markdown", action="store_true", help="Print the mapping and workload audit as Markdown")
    args = parser.parse_args()
    with SessionLocal() as db:
        result = validate_training_curriculum(db)
        if args.markdown:
            print(_markdown_report(db, result))
        else:
            print(json.dumps(result, indent=2, default=str))
    return 0 if result["valid"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
