import { useEffect, useMemo, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import {
  createServiceDeskAttempt, getServiceDeskAttempt, getServiceDeskKnowledge,
  getServiceDeskOverview, getServiceDeskPerformance, getServiceDeskQueue, serviceDeskAction,
} from "../services/api";

const tabs = ["Overview", "Work Queue", "Performance", "Knowledge Base"];
const toolNames = { ticket: "Ticket", directory: "Employee Directory", identity: "Identity & Access", bitlocker: "BitLocker Recovery", onboarding: "Onboarding", notes: "Resolution Notes", help: "Learning Help" };

function actionPayload(action, facts, note) {
  const requester = facts?.requester || {};
  const device = facts?.device || {};
  const defaults = {
    verify_identity: { verification_method: "employee_id_last4" }, search_account: { query: requester.username || "" },
    unlock_account: { account_id: requester.username || "" }, reset_password: { account_id: requester.username || "" }, reset_mfa: { account_id: requester.username || "" },
    verify_device: { device_id: device.name || "" }, lookup_recovery_key: { device_id: device.name || "" },
    verify_onboarding_request: { request_id: facts?.ticket_number || "" }, create_account: { account_id: requester.username || "" },
    assign_group: { group: requester.department === "Customer Success" ? "customer-success" : "" }, assign_device: { device_id: device.name || "" },
    add_resolution_note: { note: note || "Verified request and completed the approved simulated support action." },
  };
  return defaults[action] || {};
}

function Status({ children }) { return <span className="rounded-full bg-blue-100 px-2 py-1 text-xs font-semibold text-blue-800 dark:bg-blue-950 dark:text-blue-200">{children}</span>; }

export default function ServiceDeskPage() {
  const [params, setParams] = useSearchParams();
  const [tab, setTab] = useState(params.get("tab") || "Overview");
  const [overview, setOverview] = useState(null); const [queue, setQueue] = useState([]); const [performance, setPerformance] = useState(null); const [articles, setArticles] = useState([]);
  const [attempt, setAttempt] = useState(null); const [tool, setTool] = useState("ticket"); const [note, setNote] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const refresh = async () => { setLoading(true); setError(""); try { const [o, q, p, k] = await Promise.all([getServiceDeskOverview({ suppressToast: true }), getServiceDeskQueue({ suppressToast: true }), getServiceDeskPerformance({ suppressToast: true }), getServiceDeskKnowledge("", { suppressToast: true })]); setOverview(o.data); setQueue(q.data); setPerformance(p.data); setArticles(k.data); } catch (err) { setError(err.userMessage || "Service Desk Lab is unavailable."); } finally { setLoading(false); } };
  useEffect(() => { refresh(); }, []);
  useEffect(() => { const id = params.get("attempt"); if (id) getServiceDeskAttempt(id, { suppressToast: true }).then((res) => { setAttempt(res.data); setTab("Workspace"); }).catch(() => setError("This attempt is unavailable.")); }, [params]);
  const setWorkspaceTab = (next) => { setTab(next); setParams(next === "Workspace" && attempt ? { attempt: attempt.id } : { tab: next }); };
  const start = async (item, mode = "learning") => { try { const res = await createServiceDeskAttempt(item.id, mode); setAttempt(res.data); setTool("ticket"); setWorkspaceTab("Workspace"); } catch (err) { setMessage(err.userMessage || "Unable to start this scenario."); } };
  const submit = async (action) => { if (!attempt) return; try { const res = await serviceDeskAction(attempt.id, { action, payload: actionPayload(action, attempt.scenario.student_facts, note), expected_state_version: attempt.state_version, idempotency_key: `${action}-${attempt.state_version}-${Date.now()}` }); setAttempt(res.data.attempt); setMessage(res.data.feedback); if (action === "add_resolution_note") setNote(""); if (res.data.attempt.status !== "in_progress") refresh(); } catch (err) { setMessage(err.userMessage || "Action could not be completed."); } };
  const actions = useMemo(() => (attempt?.allowed_actions || []).filter((item) => item.tool === tool), [attempt, tool]);
  if (loading) return <main className="mx-auto max-w-7xl p-6">Loading Service Desk Lab…</main>;
  if (error) return <main className="mx-auto max-w-3xl p-6"><h1 className="text-2xl font-bold">Service Desk Lab</h1><p className="mt-3 text-slate-600 dark:text-slate-300">{error}</p><Link className="btn-secondary mt-5" to="/">Return to Nexus</Link></main>;
  return <main className="mx-auto max-w-7xl p-4 md:p-6"><header className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold text-blue-600">PRIVATE BETA</p><h1 className="text-3xl font-bold">Service Desk Lab</h1><p className="text-slate-600 dark:text-slate-300">Practice realistic IT support work.</p></div><Link className="btn-secondary" to="/">Exit to Nexus</Link></header>
    <nav aria-label="Service Desk sections" className="mb-6 flex gap-2 overflow-x-auto border-b border-slate-200 pb-2 dark:border-slate-700">{tabs.map((item) => <button key={item} type="button" onClick={() => setWorkspaceTab(item)} className={tab === item ? "btn-primary whitespace-nowrap" : "btn-secondary whitespace-nowrap"}>{item}</button>)}</nav>
    {tab === "Overview" ? <Overview data={overview} start={start} /> : null}
    {tab === "Work Queue" ? <Queue items={queue} start={start} /> : null}
    {tab === "Performance" ? <Performance data={performance} /> : null}
    {tab === "Knowledge Base" ? <Knowledge articles={articles} setArticles={setArticles} /> : null}
    {tab === "Workspace" && attempt ? <Workspace attempt={attempt} tool={tool} setTool={setTool} actions={actions} note={note} setNote={setNote} submit={submit} message={message} /> : null}
  </main>;
}

function Overview({ data, start }) { const recommended = data?.recommended; return <section className="space-y-5"><div className="panel"><h2 className="text-xl font-bold">Recommended</h2>{recommended ? <><p className="mt-2 font-semibold">{recommended.title}</p><p className="text-sm text-slate-600 dark:text-slate-300">{recommended.ticket_number} · {recommended.category} · {recommended.difficulty}/5 difficulty</p><button className="btn-primary mt-4" onClick={() => start(recommended, "learning")}>Start in Learning Mode</button></> : <p className="mt-2">No scenarios are available yet.</p>}</div><div className="grid gap-3 sm:grid-cols-3">{[["Completed",data?.completion_count],["Technical score",`${data?.scores?.technical || 0}%`],["Current mode",data?.current_mode || "learning"]].map(([label,value]) => <div key={label} className="panel"><p className="text-sm text-slate-500">{label}</p><p className="text-2xl font-bold capitalize">{value}</p></div>)}</div>{data?.active_attempt ? <div className="panel"><h2 className="font-bold">Continue active attempt</h2><p>{data.active_attempt.title}</p><button className="btn-secondary mt-3" onClick={() => start(data.active_attempt, data.active_attempt.mode)}>Continue</button></div> : null}</section>; }
function Queue({ items, start }) { return <section className="panel overflow-x-auto"><h2 className="mb-4 text-xl font-bold">Work Queue</h2><table className="w-full min-w-[700px] text-left text-sm"><thead><tr className="border-b"><th>Ticket</th><th>Requester</th><th>Category</th><th>Priority</th><th>Status</th><th>Mode</th><th>Action</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-b border-slate-100 dark:border-slate-800"><td className="py-3"><strong>{item.ticket_number}</strong><br />{item.title}</td><td>{item.requester}</td><td>{item.category}</td><td><Status>{item.priority}</Status></td><td>{item.status}</td><td className="capitalize">{item.mode}</td><td><button className="btn-secondary" onClick={() => start(item, item.mode)}>{item.attempt_id ? "Continue" : item.passed ? "Retry" : "Start"}</button></td></tr>)}</tbody></table></section>; }
function Performance({ data }) { return <section className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><div className="panel"><p>Completed scenarios</p><p className="text-3xl font-bold">{data?.completed_scenarios || 0}</p></div><div className="panel"><p>Attempts</p><p className="text-3xl font-bold">{data?.attempt_count || 0}</p></div></div>{data?.scenarios?.length ? data.scenarios.map((row) => <div className="panel" key={row.stable_key}><div className="flex justify-between gap-3"><h2 className="font-bold">{row.scenario}</h2><Status>{row.passed ? "Passed" : "Latest attempt"}</Status></div><p className="mt-2 text-sm">Latest {row.latest_score}% · Best {row.best_score}% · {row.attempts} attempts</p><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">Skills: {row.skills.join(", ")}</p></div>) : <div className="panel">Complete a scenario to see deterministic results here.</div>}</section>; }
function Knowledge({ articles, setArticles }) { const [query, setQuery] = useState(""); const search = async (value) => { setQuery(value); const res = await getServiceDeskKnowledge(value, { suppressToast: true }); setArticles(res.data); }; return <section><label className="sr-only" htmlFor="knowledge-search">Search knowledge articles</label><input id="knowledge-search" className="input-field mb-4" value={query} onChange={(e) => search(e.target.value)} placeholder="Search knowledge base" /> <div className="grid gap-3 md:grid-cols-2">{articles.map((article) => <article className="panel" key={article.id}><p className="text-xs font-semibold text-blue-600">{article.category}</p><h2 className="mt-1 font-bold">{article.title}</h2><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{article.content}</p></article>)}</div></section>; }
function Workspace({ attempt, tool, setTool, actions, note, setNote, submit, message }) { const facts = attempt.scenario.student_facts || {}; return <section className="grid gap-4 lg:grid-cols-[280px_minmax(0,1fr)]"><aside className="panel h-fit"><h2 className="font-bold">{facts.ticket_number}</h2><p className="mt-1 text-sm">{attempt.scenario.title}</p><p className="mt-3 text-sm"><strong>Requester:</strong> {facts.requester?.name || "Request"}</p><p className="text-sm"><strong>Department:</strong> {facts.requester?.department || "—"}</p>{facts.device ? <p className="text-sm"><strong>Device:</strong> {facts.device.name}</p> : null}<p className="mt-3"><Status>{attempt.mode === "learning" ? "Learning Mode" : "Simulation Mode"}</Status></p><h3 className="mt-4 font-semibold">Progress</h3><ul className="mt-2 space-y-1 text-xs">{Object.entries(attempt.visible_state).map(([key,value]) => <li key={key}>{value ? "✓" : "○"} {key.replaceAll("_", " ")}</li>)}</ul></aside><div className="space-y-4"><div className="panel"><h2 className="text-xl font-bold">{attempt.scenario.title}</h2><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{attempt.scenario.description}</p>{attempt.mode === "learning" ? <><h3 className="mt-4 font-semibold">Objectives</h3><ul className="list-disc pl-5 text-sm">{attempt.scenario.learning_objectives.map((item) => <li key={item}>{item}</li>)}</ul></> : null}</div><div className="flex gap-2 overflow-x-auto" aria-label="Simulated tools">{[...new Set(attempt.allowed_actions.map((item) => item.tool))].map((item) => <button key={item} type="button" onClick={() => setTool(item)} className={tool === item ? "btn-primary whitespace-nowrap" : "btn-secondary whitespace-nowrap"}>{toolNames[item] || item}</button>)}</div><div className="panel"><h2 className="font-bold">{toolNames[tool] || tool}</h2>{tool === "notes" ? <><label className="mt-3 block text-sm font-medium" htmlFor="resolution-note">Resolution note</label><textarea id="resolution-note" className="input-field mt-1 min-h-28" value={note} onChange={(e) => setNote(e.target.value)} placeholder="Record verification, approved action, and outcome. Do not include passwords or recovery keys." /></> : null}<div className="mt-4 flex flex-wrap gap-2">{actions.map((item) => <button key={item.key} className={item.key === "resolve_ticket" ? "btn-primary" : "btn-secondary"} type="button" onClick={() => submit(item.key)}>{item.key.replaceAll("_", " ")}</button>)}</div>{message ? <p className="mt-4 rounded bg-slate-100 p-3 text-sm dark:bg-slate-800" role="status">{message}</p> : null}</div>{attempt.status !== "in_progress" ? <div className="panel"><h2 className="font-bold">Deterministic result</h2><p className="mt-2">{attempt.result.feedback_summary}</p><p className="mt-2 text-2xl font-bold">{attempt.result.overall_score}%</p></div> : null}</div></section>; }
