import { ArrowLeft } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { Link, useParams, useSearchParams } from "react-router-dom";
import { getV2MentorStudent } from "../../services/api";
import { V2_MODULE_KEY } from "./V2MentorProgressPage";

const status = (value) => String(value || "not started").replaceAll("_", " ");
const conceptLabel = (value) => typeof value === "string" ? value : value?.concept || value?.name || "Unnamed concept";

export default function V2MentorStudentPage() {
  const { studentId } = useParams();
  const [searchParams] = useSearchParams();
  const moduleKey = searchParams.get("module") || V2_MODULE_KEY;
  const [data, setData] = useState(null);
  const [error, setError] = useState("");
  const load = useCallback(() => { setError(""); getV2MentorStudent(moduleKey, studentId, { suppressToast: true }).then((res) => setData(res.data)).catch((err) => setError(err?.userMessage || "Student detail could not be loaded.")); }, [moduleKey, studentId]);
  useEffect(load, [load]);
  if (error && !data) return <main className="mx-auto max-w-4xl p-6"><div className="panel" role="alert"><h1 className="font-bold">Student detail unavailable</h1><p>{error}</p><button className="btn-primary mt-4" onClick={load}>Try again</button></div></main>;
  if (!data) return <main className="mx-auto max-w-5xl p-6" role="status">Loading student module report...</main>;
  return <main className="mx-auto max-w-6xl space-y-6 p-4 pb-16 sm:p-6"><Link className="inline-flex items-center gap-2 text-sm font-semibold text-blue-600" to="/admin/v2-progress"><ArrowLeft size={16} />Back to cohort</Link><header><p className="text-sm font-semibold text-blue-600">{data.certification.name} · {data.certification.version}</p><h1 className="mt-1 text-3xl font-bold">{data.student_name}</h1><p className="mt-2 text-slate-600 dark:text-slate-300">{data.module_title}</p><p className="mt-2 font-semibold">Current activity: {data.current_position.title}</p></header>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4" aria-label="Progress summary"><div className="panel"><p className="text-sm text-slate-500">Lessons</p><p className="mt-1 text-xl font-bold">{data.completion.lessons_completed} / {data.completion.lessons_total}</p></div><div className="panel"><p className="text-sm text-slate-500">Required resources</p><p className="mt-1 text-xl font-bold">{data.completion.required_resources_completed} / {data.completion.required_resources_total}</p></div><div className="panel"><p className="text-sm text-slate-500">Module Quiz</p><p className="mt-1 text-xl font-bold capitalize">{data.module_quiz.score != null ? `${data.module_quiz.score}% · ` : ""}{status(data.module_quiz.status)}</p></div><div className="panel"><p className="text-sm text-slate-500">Module completion</p><p className="mt-1 text-xl font-bold">{data.completion.module_complete ? "Complete" : "In progress"}</p></div></section>
    <div className="grid gap-6 lg:grid-cols-3"><section className="panel"><h2 className="text-xl font-bold">Required resources</h2>{data.required_resources.length ? <ul className="mt-3 space-y-2">{data.required_resources.map((row) => <li key={row.resource_key}><strong>{row.resource}</strong><p className="text-sm text-slate-500">{row.lesson} · {row.completed ? "Completed" : "Incomplete"}</p></li>)}</ul> : <p className="mt-3 text-slate-500">No required resources configured.</p>}</section><section className="panel"><h2 className="text-xl font-bold">Quick Checks</h2>{data.quick_checks.length ? <ul className="mt-3 space-y-2">{data.quick_checks.map((row) => <li key={row.assessment_key}><strong>{row.title}</strong> — <span className="capitalize">{status(row.status)}</span>{row.score != null ? ` (${row.score}%)` : ""}</li>)}</ul> : <p className="mt-3 text-slate-500">No Quick Checks configured.</p>}</section><section className="panel"><h2 className="text-xl font-bold">Weak Areas</h2>{data.weak_objectives.length ? <ul className="mt-3 space-y-3">{data.weak_objectives.map((row) => <li key={row.objective_code}><strong>{row.objective_code} — {row.objective_text}</strong><p className="text-sm text-slate-500">{row.missed_count} assessment misses</p></li>)}</ul> : <p className="mt-3 text-slate-500">No weak objectives identified.</p>}</section></div>
    <section aria-labelledby="missed-heading"><h2 id="missed-heading" className="text-xl font-bold">Missed Questions</h2>{data.missed_questions.length ? <div className="mt-3 space-y-4">{data.missed_questions.map((row) => <article className="panel" key={row.question_id}><div className="flex flex-wrap justify-between gap-2"><p className="font-bold">{row.question_text}</p><span className="text-sm font-semibold text-rose-700 dark:text-rose-300">Missed {row.times_missed} time{row.times_missed === 1 ? "" : "s"}</span></div><dl className="mt-3 grid gap-2 text-sm"><div><dt className="font-semibold">Student answer</dt><dd>{row.student_answer || "Not retained in the earlier activity record"}</dd></div><div><dt className="font-semibold">Correct answer</dt><dd>{row.correct_answer.join(", ")}</dd></div><div><dt className="font-semibold">Why</dt><dd>{row.explanation}</dd></div><div><dt className="font-semibold">Objective / topic</dt><dd>{row.objective_code} — {row.objective_text} · {row.topic}</dd></div></dl></article>)}</div> : <p className="panel mt-3 text-slate-500">No missed Nexus questions recorded.</p>}</section>
    <section aria-labelledby="explain-heading"><h2 id="explain-heading" className="text-xl font-bold">Explain Responses</h2>{data.explain_responses.length ? <div className="mt-3 space-y-4">{data.explain_responses.map((row) => <article className="panel" key={row.submission_ref}><div className="flex flex-wrap justify-between gap-2"><strong>{row.prompt}</strong><span className="capitalize text-sm">{status(row.status)}</span></div><p className="mt-3 whitespace-pre-wrap rounded-xl bg-slate-50 p-3 dark:bg-slate-800">{row.submitted_answer}</p><p className="mt-3 text-sm"><strong>Expected concepts:</strong> {row.expected_concepts.map(conceptLabel).join(", ")}</p><p className="mt-1 text-sm"><strong>Rubric:</strong> {row.rubric_version || "Unversioned"} · deterministic {status(row.deterministic?.status)}{row.confidence != null ? ` · AI confidence ${Math.round(row.confidence * 100)}%` : ""}</p><p className="mt-1 text-sm"><strong>Resolved:</strong> {row.resolved.grade_source || "Pending"}{row.resolved.score != null ? ` · ${Math.round(row.resolved.score * 100)}%` : ""}</p>{row.mentor_overrides.length ? <details className="mt-3"><summary className="cursor-pointer font-semibold">Mentor override history ({row.mentor_overrides.length})</summary><ul className="mt-2 space-y-2">{row.mentor_overrides.map((item) => <li key={item.id}>{item.override_passed ? "Pass" : "Not passed"} · {item.reason}</li>)}</ul></details> : null}{row.status !== "graded" ? <Link className="btn-primary mt-4 inline-flex" to={`/admin/v2-grading/${row.pending_grade_id}`}>Grade response</Link> : null}</article>)}</div> : <p className="panel mt-3 text-slate-500">No Explain responses submitted.</p>}</section>
    <div className="grid gap-6 lg:grid-cols-2"><section className="panel"><h2 className="text-xl font-bold">Practical</h2><p className="mt-2 capitalize">{status(data.practical?.status)}{data.practical?.score != null ? ` · ${data.practical.score}%` : ""}</p>{data.practical?.feedback ? <p className="mt-2">{data.practical.feedback}</p> : null}{data.practical?.notes ? <p className="mt-2 text-sm">Evidence note: {data.practical.notes}</p> : null}<Link className="btn-secondary mt-4 inline-flex" to={data.practical?.review_url || "/admin/labs"}>Open Lab review</Link></section><section className="panel"><h2 className="text-xl font-bold">Service Desk</h2><p className="mt-2 capitalize">{status(data.service_desk?.status)}{data.service_desk?.score != null ? ` · ${data.service_desk.score}%` : ""}</p>{data.service_desk?.breakdown?.length ? <ul className="mt-3 grid grid-cols-2 gap-2">{data.service_desk.breakdown.map((row) => <li key={row.key}>{row.label}: <strong>{row.met ? "Met" : "Needs work"}</strong></li>)}</ul> : null}<Link className="btn-secondary mt-4 inline-flex" to={data.service_desk?.review_url || "/admin/service-desk-review"}>Open Service Desk Review</Link></section></div>
    <section aria-labelledby="external-heading"><h2 id="external-heading" className="text-xl font-bold">Self-reported external practice</h2><p className="mt-1 text-sm text-slate-500">Reported scores do not affect Nexus mastery or completion.</p>{data.external_practice.length ? <div className="mt-3 space-y-3">{data.external_practice.map((row) => <article className="panel" key={row.resource_key}><strong>{row.resource}</strong><p className="mt-1 text-sm">{row.completed ? "Completed" : "Not marked complete"}{row.reported_score != null ? ` · Reported score: ${row.reported_score}` : ""}</p>{row.student_note ? <p className="mt-2">Student note: “{row.student_note}”</p> : null}{row.confusing_topic ? <p>Confusing topic: {row.confusing_topic}</p> : null}{row.question_for_mentor ? <p className="font-semibold">Question for mentor: {row.question_for_mentor}</p> : null}</article>)}</div> : <p className="panel mt-3 text-slate-500">No external-practice self-reports.</p>}</section>
  </main>;
}
