import { ArrowLeft } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { getMentorGrade, submitMentorGrade } from "../../services/api";

export default function V2MentorGradePage() {
  const { pendingGradeId } = useParams();
  const [data, setData] = useState(null);
  const [form, setForm] = useState({ score: 0.7, passed: true, reason: "" });
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const load = useCallback(() => { setError(""); getMentorGrade(pendingGradeId, { suppressToast: true }).then((res) => setData(res.data)).catch((err) => setError(err?.userMessage || "Grading detail could not be loaded.")); }, [pendingGradeId]);
  useEffect(load, [load]);
  async function submit(event) { event.preventDefault(); setBusy(true); setError(""); try { const res = await submitMentorGrade(pendingGradeId, { score: Number(form.score), passed: form.passed, reason: form.reason, mentor_label: "mentor" }, { suppressToast: true }); setData(res.data.history); setForm((old) => ({ ...old, reason: "" })); } catch (err) { setError(err?.userMessage || "The mentor grade could not be saved."); } finally { setBusy(false); } }
  if (error && !data) return <main className="mx-auto max-w-3xl p-6" role="alert">{error}</main>;
  if (!data) return <main className="mx-auto max-w-3xl p-6" role="status">Loading response...</main>;
  return <main className="mx-auto max-w-4xl space-y-6 p-4 pb-16 sm:p-6"><Link className="inline-flex items-center gap-2 text-sm font-semibold text-blue-600" to="/admin/v2-progress"><ArrowLeft size={16} />Back to mentor progress</Link><header><p className="text-sm font-semibold text-amber-700">Mentor grading</p><h1 className="mt-1 text-3xl font-bold">Review Explain response</h1><p className="mt-2 capitalize text-slate-500">{data.status?.replaceAll("_", " ")} · Student #{data.student_id}</p></header>{error ? <p className="rounded-xl bg-rose-50 p-3 text-rose-700" role="alert">{error}</p> : null}<section className="panel"><h2 className="font-bold">Prompt</h2><p className="mt-2">{data.question_text}</p><h2 className="mt-5 font-bold">Student answer</h2><p className="mt-2 whitespace-pre-wrap rounded-xl bg-slate-50 p-4 dark:bg-slate-800">{data.submitted_answer}</p><h2 className="mt-5 font-bold">Expected concepts / rubric</h2><p className="mt-2">{data.deterministic?.matched_concepts?.length ? `Matched: ${data.deterministic.matched_concepts.join(", ")}. ` : ""}{data.deterministic?.missing_concepts?.length ? `Missing: ${data.deterministic.missing_concepts.join(", ")}.` : "Review against the stored rubric version."}</p><p className="mt-2 text-sm text-slate-500">Rubric version: {data.rubric_version || "Unversioned"}</p></section><form className="panel" onSubmit={submit}><h2 className="text-xl font-bold">Assign manual grade</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="font-semibold">Score (0–1)<input className="input-field mt-1 w-full" type="number" min="0" max="1" step="0.01" value={form.score} onChange={(event) => setForm({ ...form, score: event.target.value })} required /></label><label className="font-semibold">Result<select className="input-field mt-1 w-full" value={String(form.passed)} onChange={(event) => setForm({ ...form, passed: event.target.value === "true" })}><option value="true">Pass</option><option value="false">Not passed</option></select></label></div><label className="mt-4 block font-semibold">Reason / note<textarea className="input-field mt-1 min-h-28 w-full" minLength={3} maxLength={4000} value={form.reason} onChange={(event) => setForm({ ...form, reason: event.target.value })} required /></label><button className="btn-primary mt-4" disabled={busy || form.reason.trim().length < 3}>{busy ? "Saving..." : "Submit mentor grade"}</button></form><section><h2 className="text-xl font-bold">Grading history</h2>{data.mentor_overrides.length ? <ol className="mt-3 space-y-3">{[...data.mentor_overrides].reverse().map((row) => <li className="panel" key={row.id}><strong>{row.override_passed ? "Pass" : "Not passed"} · {row.override_score != null ? `${Math.round(row.override_score * 100)}%` : "No score"}</strong><p className="mt-1">{row.reason}</p><p className="mt-1 text-xs text-slate-500">{row.mentor_label}</p></li>)}</ol> : <p className="panel mt-3 text-slate-500">No mentor override has been recorded.</p>}</section></main>;
}
